# Generated by Django 5.2.9 on 2025-12-31 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alerta', '0001_initial'),
        ('Plantacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='plantacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='Plantacion.plantacion'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='recomendacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Alerta.recomendacion'),
        ),
    ]
