# Generated by Django 5.2.9 on 2026-01-02 22:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerta', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='accion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='Alerta.accion'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='fechaGeneracion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='recomendacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='Alerta.recomendacion'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipoAlerta',
            field=models.CharField(choices=[('riego', 'Riego'), ('secado', 'Secado')], max_length=50),
        ),
    ]
