# Generated by Django 5.2.9 on 2025-12-31 00:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alerta', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTomaDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoConfiguracion', models.CharField(max_length=100)),
                ('criterioDecision', models.CharField(max_length=100)),
                ('fechaConfiguracion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionUmbral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorMinimo', models.FloatField()),
                ('valorMaximo', models.FloatField()),
                ('fechaConfiguracion', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DatoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('fechaRegistro', models.DateField(default=django.utils.timezone.now)),
                ('horaRegistro', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='VariableAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCultivo', models.CharField(max_length=100)),
                ('tipoCultivo', models.CharField(max_length=100)),
                ('familia', models.CharField(max_length=100)),
                ('semilla', models.CharField(max_length=100)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to='Plantacion.configuracionumbral')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoSensor', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=30)),
                ('ubicacion', models.CharField(max_length=100)),
                ('datoSensor', models.ManyToManyField(blank=True, related_name='sensores', to='Plantacion.datosensor')),
            ],
        ),
        migrations.CreateModel(
            name='Plantacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fechaRegistro', models.DateField(default=django.utils.timezone.now)),
                ('espacio', models.FloatField()),
                ('alerta', models.ManyToManyField(blank=True, related_name='plantaciones', to='Alerta.alerta')),
                ('configuracionTomaDecision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Plantacion.configuraciontomadecision')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plantacion.cultivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantaciones', to='users.usuario')),
                ('sensores', models.ManyToManyField(related_name='plantaciones', to='Plantacion.sensor')),
            ],
        ),
        migrations.AddField(
            model_name='datosensor',
            name='variableAmbiental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plantacion.variableambiental'),
        ),
        migrations.AddField(
            model_name='configuracionumbral',
            name='variableAmbiental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plantacion.variableambiental'),
        ),
    ]
