# Generated by Django 5.2.9 on 2026-01-02 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plantacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantacion',
            name='alerta',
        ),
    ]
